name: test
on: [push]

jobs:
  Run-on-ubuntu:
    name: Run on ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        git submodule update --init --recursive
        sudo apt install nasm
        make clean
        make CXX=clang++
        go test -v ./bls

  Run-on-Intel-macos:
    name: Run on Intel macos
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.18.x'
    - run: |
        git submodule update --init --recursive
        brew install nasm
        make clean
        make
        go test -v ./bls

  Run-on-ARM-macos:
    name: Run on macos
    # Intel Mac
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.18.x'
    - run: |
        git submodule update --init --recursive
        make clean
        make
        go test -v ./bls

  Run-on-windows:
    name: Run on windows
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        #msystem: UCRT64
        update: true
        platform-check-severity: warn
        install: >-
          make
          python3
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-go
    - uses: msys2/setup-msys2@v2
    # - uses: actions/checkout@v4
    - run: |
        git clone -b release https://github.com/herumi/bls-go-binary
        cd bls-go-binary
        #git submodule update --init --recursive
        #make MCL_STATIC_CODE=0
        go test -v ./bls
